"""Add template_id and template_version to mcp_service_templates

Revision ID: 12ebcecda7af
Revises: ce9e3b9ee735
Create Date: 2026-01-14 12:36:33.174437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12ebcecda7af'
down_revision = 'ce9e3b9ee735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the new columns to mcp_service_templates
    with op.batch_alter_table('mcp_service_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('template_version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_service_templates', schema=None) as batch_op:
        batch_op.drop_column('template_version')
        batch_op.drop_column('template_id')
    # ### end Alembic commands ###

    with op.batch_alter_table('login_lock_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_lock_status_ip_address'))
        batch_op.create_index(batch_op.f('ix_login_lock_status_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ip_address'), ['ip_address'], unique=True)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('mcp_service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('account_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_account_capability'), ['account_id', 'capability_id'], unique=True)

    # ### end Alembic commands ###
