"""Add unique constraint for capability name per app

Revision ID: 18b39d17f174
Revises: 553ba3ed9069
Create Date: 2025-11-18 16:42:55.108337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b39d17f174'
down_revision = '553ba3ed9069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_capability_app_name', ['app_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_capability_app_name', type_='unique')

    # ### end Alembic commands ###
