"""Auto migration

Revision ID: 3b81aca73e8a
Revises: ad33b08ca7d7
Create Date: 2025-12-02 09:46:14.632888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b81aca73e8a'
down_revision = 'ad33b08ca7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), server_default='value', nullable=False))
        batch_op.add_column(sa.Column('env_var_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_column('env_var_name')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
