"""Add MCP Services table and migrate existing apps

Revision ID: a39dd60460a1
Revises: c8c9d39f9c77
Create Date: 2025-11-18 17:03:55.986038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'a39dd60460a1'
down_revision = 'c8c9d39f9c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create mcp_services table
    op.create_table('mcp_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    
    # 2. Add mcp_service_id to apps and make subdomain nullable
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcp_service_id', sa.Integer(), nullable=True))
        batch_op.alter_column('subdomain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key('fk_apps_mcp_service_id', 'mcp_services', ['mcp_service_id'], ['id'])
    
    # 3. Migrate existing apps: create one MCP service per app
    conn = op.get_bind()
    apps = conn.execute(text("SELECT id, name, subdomain, description, is_enabled, created_at, updated_at FROM apps WHERE subdomain IS NOT NULL")).fetchall()
    
    for app in apps:
        # Create MCP service for each existing app
        result = conn.execute(
            text("INSERT INTO mcp_services (name, subdomain, description, is_enabled, created_at, updated_at) VALUES (:name, :subdomain, :description, :is_enabled, :created_at, :updated_at)"),
            {
                'name': app[1],  # Use app name as MCP service name
                'subdomain': app[2],
                'description': app[3],
                'is_enabled': app[4],
                'created_at': app[5],
                'updated_at': app[6]
            }
        )
        mcp_service_id = result.lastrowid
        
        # Link app to the new MCP service
        conn.execute(
            text("UPDATE apps SET mcp_service_id = :mcp_service_id WHERE id = :app_id"),
            {'mcp_service_id': mcp_service_id, 'app_id': app[0]}
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_apps_mcp_service_id', type_='foreignkey')
        batch_op.alter_column('subdomain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('mcp_service_id')

    op.drop_table('mcp_services')
    # ### end Alembic commands ###
