"""Add security audit logging tables

Revision ID: ce9e3b9ee735
Revises: d1e2f3a4b5c6
Create Date: 2026-01-08 10:00:20.764258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce9e3b9ee735'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create admin_login_logs table
    op.create_table(
        'admin_login_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('username', sa.String(100), nullable=False),
        sa.Column('ip_address', sa.String(45), nullable=False),
        sa.Column('user_agent', sa.String(500), nullable=True),
        sa.Column('is_success', sa.Boolean(), nullable=False),
        sa.Column('failure_reason', sa.String(255), nullable=True),
        sa.Column('session_id', sa.String(255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_login_logs_created_at', 'admin_login_logs', ['created_at'])
    op.create_index('ix_admin_login_logs_username', 'admin_login_logs', ['username'])
    op.create_index('ix_admin_login_logs_ip_address', 'admin_login_logs', ['ip_address'])
    
    # Create admin_action_logs table
    op.create_table(
        'admin_action_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('admin_username', sa.String(100), nullable=False),
        sa.Column('action_type', sa.String(50), nullable=False),
        sa.Column('resource_type', sa.String(50), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('resource_name', sa.String(255), nullable=True),
        sa.Column('changes', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.String(500), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_action_logs_created_at', 'admin_action_logs', ['created_at'])
    op.create_index('ix_admin_action_logs_admin_username', 'admin_action_logs', ['admin_username'])
    op.create_index('ix_admin_action_logs_action_type', 'admin_action_logs', ['action_type'])
    op.create_index('ix_admin_action_logs_resource_type', 'admin_action_logs', ['resource_type'])
    
    # Create login_lock_status table
    op.create_table(
        'login_lock_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ip_address', sa.String(45), nullable=False),
        sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ip_address')
    )
    op.create_index('ix_login_lock_status_ip_address', 'login_lock_status', ['ip_address'])
    op.create_index('ix_login_lock_status_locked_until', 'login_lock_status', ['locked_until'])
    
    # Skip problematic index drop (it's being handled automatically by MySQL)
    # with op.batch_alter_table('account_permissions', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('uq_account_capability'))

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('mcp_service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mcp_capability_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mcp_capability_templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mcp_service_templates', ['template_id'], ['id'])

    with op.batch_alter_table('mcp_connection_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_connection_logs_created_at_desc'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_connection_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_connection_logs_created_at_desc'), ['created_at'], unique=False)

    with op.batch_alter_table('mcp_capability_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mcp_capability_templates_ibfk_1'), 'mcp_service_templates', ['template_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('mcp_service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # Skip problematic index recreation
    # with op.batch_alter_table('account_permissions', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('uq_account_capability'), ['account_id', 'capability_id'], unique=True)

    # Drop security audit logging tables
    op.drop_index('ix_login_lock_status_locked_until', 'login_lock_status')
    op.drop_index('ix_login_lock_status_ip_address', 'login_lock_status')
    op.drop_table('login_lock_status')
    
    op.drop_index('ix_admin_action_logs_resource_type', 'admin_action_logs')
    op.drop_index('ix_admin_action_logs_action_type', 'admin_action_logs')
    op.drop_index('ix_admin_action_logs_admin_username', 'admin_action_logs')
    op.drop_index('ix_admin_action_logs_created_at', 'admin_action_logs')
    op.drop_table('admin_action_logs')
    
    op.drop_index('ix_admin_login_logs_ip_address', 'admin_login_logs')
    op.drop_index('ix_admin_login_logs_username', 'admin_login_logs')
    op.drop_index('ix_admin_login_logs_created_at', 'admin_login_logs')
    op.drop_table('admin_login_logs')

    # ### end Alembic commands ###
